In [ ]:
#Practica 30
import pandas as pd
agosto2014 = pd.read_excel(r"C:\Users\formacio\Desktop\clases python\VentasGroucery_Meses.xlsx", 
                           sheet_name="Ventas Agosto 2014")
septiembre2014 = pd.read_excel(r"C:\Users\formacio\Desktop\clases python\VentasGroucery_Meses.xlsx", 
                           sheet_name="Ventas Septiembre 2014")
octubre2014 = pd.read_excel(r"C:\Users\formacio\Desktop\clases python\VentasGroucery_Meses.xlsx", 
                           sheet_name="Ventas Octubre 2014")
#concatenar
trimestre = pd.concat([agosto2014,septiembre2014,octubre2014],ignore_index=True)
#filtrar las unidades mayores de 10
filtro = trimestre['Quantity']>10
trimestre = trimestre[filtro]
#Calcular Amount
trimestre['Amount'] = trimestre['Unit Price']*trimestre['Quantity']
#Un objeto que almacene la agrupación
resultado = round(trimestre.groupby(['Ship Country','Category']).Amount.sum(),2)
resultado = pd.DataFrame(resultado).reset_index()
#Guardar directo
resultado.to_excel(r"C:\temp\Practica30.xlsx",sheet_name="Trimestre 2014", header=True,index=True)
print("Succesfully")

In [ ]:
import pandas as pd
pedidos = pd.read_excel(r"C:\Users\formacio\Desktop\clases python\Pedidos.xlsx", sheet_name="Pedidos")
pedidos

In [ ]:

detallespedidos = pd.read_excel(r"C:\Users\formacio\Desktop\clases python\Detalles Pedidos.xlsx",
                                sheet_name="Detalles Pedidos")
detallespedidos
#combinar dos dataframes, mediante merch. Necesitamos tener un campo en comun, no tienen q llamarse igual
merge_pedidos = pd.merge(pedidos,detallespedidos, on="Id. de pedido", how="inner")
merge_pedidos
#si no se llaman igual, left_on + right_on
#merge_pedidos = pd.merge(pedidos,detallespedidos, left_on=on="Id de pedido",right_on="pedido Id")
#el tema del join, por defecto es inner

PRACTICA 31: CARGAREMOS Y COMBIONAREMOS LOS SIG FICHEROS DE EXCEL
-Pedidos.xlsx
-Detalles Pedidos.xlsx
-Productos.xlsx
-Categorias.xlsx
-Comerciales.xlsx

31.1: REALIZAREMOS LAS TRANSFORMACIONES PARA GUARDAR EN UN FICHERO DE EXCEL UN CONJUNTO DE DATOS QUE CONTENGA EL NOMBRE DE LA CATEGORIA, 
AGRUPADA POR LA SUMA DE IMPORTE (IMPORTE = PRECIO UNIDAD*CANTIDAD), NUMERO DE PEDIDOS, PROMEDIO DE CANTIDAD

31.2: REALIZAREMOS LAS TRANSFORMACIONES PARA GUARDAR EN UN FICHERO DE EXCEL UN CONJUNTO
DE DATOS QUE CONTENGA EL NOMBRE DEL COMERCIAL, AGRUPADA POR NUMERO DE PEDIDOS

31.3: REALIZAREMOS LAS TRANSFORMACIONES PARA GUARDAR ENM UN FICHERO DE EXCEL UN CONJUNTO DE DATOS QUE CONTENGA EL NOMBRE DEL MES EN LETRAS
DE LA FECHA DE PEDIDOS, AGRUPADA POR SUMA DE IMPORTE

In [ ]:
#PRACTICA 31:
productos = pd.read_excel(r"C:\Users\formacio\Desktop\clases python\Productos.xlsx", sheet_name="Productos")
productos

In [ ]:
categorias = pd.read_excel(r"C:\Users\formacio\Desktop\clases python\Categorías.xlsx", sheet_name="Categorías")
categorias

In [ ]:
comerciales = pd.read_excel(r"C:\Users\formacio\Desktop\clases python\Comerciales.xlsx", sheet_name="Comerciales")
comerciales

In [ ]:
pedidos_productos = pd.merge(merge_pedidos, productos, left_on="Producto", right_on="Nombre de producto")
pedidos_productos

In [ ]:
pedidos_productos_categorias = pd.merge(pedidos_productos, categorias, left_on="Categoría", right_on="Nombre de categoría")
pedidos_productos_categorias

In [ ]:
ficheros_combinados = pd.merge(pedidos_productos_categorias, comerciales, on="Id. de Comercial")
ficheros_combinados.info()

In [102]:
#PRACTICA 31.1:
ficheros_combinados['Importe'] = ficheros_combinados['Precio por unidad']*ficheros_combinados['Cantidad']
ficheros_combinados

,Id. de pedido,Id. de Cliente,Id. de Comercial,Fecha de pedido,Fecha de entrega,Fecha de envío,Forma de envío,Cargo,Nombre de destinatario,Dirección de destinatario,...,Proveedor,Categoría,Cantidad por unidad,Id. de categoría,Nombre de categoría,Descripción,Imagen,Apellidos,Nombre,Importe
0,10248,WILMK,5,1996-07-04,1996-08-01,1996-07-16,Federal Shipping,32.38,Wilman Kala,Keskuskatu 45,...,Cooperativa de Quesos 'Las Cabras',Lácteos,paq. 1 kg,4,Lácteos,Quesos,NaN,Buchanan,Steven,168.0
1,10248,WILMK,5,1996-07-04,1996-08-01,1996-07-16,Federal Shipping,32.38,Wilman Kala,Keskuskatu 45,...,Leka Trading,Granos/Cereales,32 - 1 kg paq.,5,Granos/Cereales,"Pan, galletas, pasta y cereales",NaN,Buchanan,Steven,98.0
2,10248,WILMK,5,1996-07-04,1996-08-01,1996-07-16,Federal Shipping,32.38,Wilman Kala,Keskuskatu 45,...,Formaggi Fortini s.r.l.,Lácteos,24 - paq. 200 g,4,Lácteos,Quesos,NaN,Buchanan,Steven,174.0
3,10249,TOMSP,6,1996-07-05,1996-08-16,1996-07-10,Speedy Express,11.61,Toms Spezialitäten,Luisenstr. 48,...,Mayumi's,Frutas/Verduras,40 - paq. 100 g,7,Frutas/Verduras,Frutas secas y queso de soja,NaN,Suyama,Michael,167.4
4,10249,TOMSP,6,1996-07-05,1996-08-16,1996-07-10,Speedy Express,11.61,Toms Spezialitäten,Luisenstr. 48,...,"G'day, Mate",Frutas/Verduras,50 - paq. 300 g,7,Frutas/Verduras,Frutas secas y queso de soja,NaN,Suyama,Michael,1696.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2150,11077,RATTC,1,1998-05-06,1998-06-03,NaT,United Package,8.53,Rattlesnake Canyon Grocery,2817 Milton Dr.,...,Plutzer Lebensmittelgroßmärkte AG,Granos/Cereales,20 bolsas x 4 porc.,5,Granos/Cereales,"Pan, galletas, pasta y cereales",NaN,Davolio,Nancy,66.5
2151,11077,RATTC,1,1998-05-06,1998-06-03,NaT,United Package,8.53,Rattlesnake Canyon Grocery,2817 Milton Dr.,...,New Orleans Cajun Delights,Condimentos,24 - frascos 8 l,2,Condimentos,"Salsas dulces y picantes, delicias, comida par...",NaN,Davolio,Nancy,17.0
2152,11077,RATTC,1,1998-05-06,1998-06-03,NaT,United Package,8.53,Rattlesnake Canyon Grocery,2817 Milton Dr.,...,Svensk Sjöföda AB,Pescado/Marisco,24 - frascos150 g,8,Pescado/Marisco,"Pescados, mariscos y algas",NaN,Davolio,Nancy,30.0
2153,11077,RATTC,1,1998-05-06,1998-06-03,NaT,United Package,8.53,Rattlesnake Canyon Grocery,2817 Milton Dr.,...,Plutzer Lebensmittelgroßmärkte AG,Bebidas,"24 - bot. 0,5 l",1,Bebidas,"Gaseosas, café, té, cervezas y maltas",NaN,Davolio,Nancy,31.0
2154,11077,RATTC,1,1998-05-06,1998-06-03,NaT,United Package,8.53,Rattlesnake Canyon Grocery,2817 Milton Dr.,...,Plutzer Lebensmittelgroßmärkte AG,Condimentos,12 cajas,2,Condimentos,"Salsas dulces y picantes, delicias, comida par...",NaN,Davolio,Nancy,26.0

In [ ]:
importe_categoria = round(ficheros_combinados.groupby(['Categoría']).Importe.sum(),2)
importe_categoria = pd.DataFrame(importe_categoria).reset_index()
importe_categoria

In [ ]:
pedidos_categoria = round(ficheros_combinados.groupby(['Categoría'])['Id. de pedido'].count(),2)
pedidos_categoria = pd.DataFrame(pedidos_categoria).reset_index()
pedidos_categoria

In [99]:
promedio_categoria = round(ficheros_combinados.groupby(['Categoría']).Cantidad.mean(),2)
pedidos_categoria = pd.DataFrame(pedidos_categoria).reset_index()
pedidos_categoria

   level_0  index        Categoría  Id. de pedido
0        0      0          Bebidas            404
1        1      1           Carnes            173
2        2      2      Condimentos            216
3        3      3  Frutas/Verduras            136
4        4      4  Granos/Cereales            196
5        5      5          Lácteos            366
6        6      6  Pescado/Marisco            330
7        7      7       Repostería            334

In [100]:
agrupado = pd.merge(importe_categoria, pedidos_categoria, on='Categoría')
agrupado = pd.merge(agrupado,promedio_categoria, on="Categoría")
print(agrupado)

agrupado.to_excel(r"C:\Temp\Combinado.xlsx",sheet_name="Categorias",header=True, index=False)
print("Terminado")

         Categoría    Importe  level_0  index  Id. de pedido  Cantidad
0          Bebidas  286526.95        0      0            404     23.59
1           Carnes  178188.80        1      1            173     24.27
2      Condimentos  113694.75        2      2            216     24.53
3  Frutas/Verduras  105268.60        3      3            136     21.99
4  Granos/Cereales  100726.80        4      4            196     23.28
5          Lácteos  251330.50        5      5            366     25.00
6  Pescado/Marisco  141623.09        6      6            330     23.28
7       Repostería  177099.10        7      7            334     23.67
Terminado

In [ ]:
#PRACTICA 31.2 REALIZAREMOS LAS TRANSFORMACIONES PARA GUARDAR EN UN FICHERO DE EXCEL UN CONJUNTO 
#DE DATOS QUE CONTENGA EL NOMBRE DEL COMERCIAL, AGRUPADA POR NUMERO DE PEDIDOS
# ****terminarlo en casa
pedidos_categoria = round(ficheros_combinados.groupby(['Proveedor'])['Id. de pedido'].count(),2)
pedidos_categoria = pd.DataFrame(pedidos_categoria).reset_index()
pedidos_categoria

                                 Proveedor  Id. de pedido
0               Aux joyeux ecclésiastiques             54
1                        Bigfoot Breweries             65
2       Cooperativa de Quesos 'Las Cabras'             52
3                       Escargots Nouveaux             18
4                           Exotic Liquids             94
5                  Formaggi Fortini s.r.l.            104
6                         Forêts d'érables             72
7                              G'day, Mate             98
8                             Gai pâturage            105
9                Grandma Kelly's Homestead             54
10             Heli Süßwaren GmbH & Co. KG             59
11                               Karkki Oy             70
12                            Leka Trading             82
13                              Lyngbysild             41
14                               Ma Maison             69
15                                Mayumi's             68
16             New England Seafood Cannery             88
17              New Orleans Cajun Delights             70
18  Nord-Ost-Fisch Handelsgesellschaft mbH             32
19                         Norske Meierier            105
20                        PB Knäckebröd AB             34
21                    Pasta Buttini s.r.l.             73
22                           Pavlova, Ltd.            163
23       Plutzer Lebensmittelgroßmärkte AG            179
24               Refrescos Americanas LTDA             51
25                Specialty Biscuits, Ltd.            126
26                       Svensk Sjöföda AB             51
27                           Tokyo Traders             51
28                     Zaanse Snoepfabriek             27

In [106]:
#31.3: REALIZAREMOS LAS TRANSFORMACIONES PARA GUARDAR ENM UN FICHERO DE EXCEL UN CONJUNTO DE DATOS QUE CONTENGA EL NOMBRE DEL MES EN LETRAS
#DE LA FECHA DE PEDIDOS, AGRUPADA POR SUMA DE IMPORTE

# el accesor de dataframe, el accesor es acceder a un grupo de metodos, mediante un punto 
ficheros_combinados['Apellidos'].str.replace('a','@')

0       Buch@n@n
1       Buch@n@n
2       Buch@n@n
3         Suy@m@
4         Suy@m@
          ...
2150     D@volio
2151     D@volio
2152     D@volio
2153     D@volio
2154     D@volio
Name: Apellidos, Length: 2155, dtype: object

In [ ]:
#el accesor de datetime es el dt, el mes en letras
ficheros_combinados['Fecha de pedido'].dt.strftime('%B')

0       July
1       July
2       July
3       July
4       July
        ...
2150     May
2151     May
2152     May
2153     May
2154     May
Name: Fecha de pedido, Length: 2155, dtype: object